### ISSUE TITLE
Amend this so it does not remove the hash of commits that are in between versions 

### ISSUE THREAD

**Issue by RachelDuffin** [moka-guys/genomics_server_download#12]
https://github.com/moka-guys/genomics_server_download/blob/203f8e56a1120a8c34736638b7965f3d39bfcdc3/git_tag.py#L8

Currently this obscures information on whether the script is running on a commit that is in between version releases (it removes the hash of the commit from the end of the version tag, which will be present for example if a commit has been made since a version)

**Comment by RachelDuffin** [comment]
An example that would exhibit the desired behaviour:

`""" This script contains the function used to obtain the git tag of the current version of the
repository
"""

import subprocess
import os


def git_tag():
    """Obtain the git tag of the current commit"""
    filepath = os.path.dirname(os.path.realpath(__file__))
    cmd = f"git -C {filepath} describe --tags"

    proc = subprocess.Popen(
        [cmd], stderr=subprocess.PIPE, stdout=subprocess.PIPE, shell=True
    )
    out, _ = proc.communicate()
    #  Return standard out, removing any new line characters
    return out.rstrip().decode("utf-8")


if __name__ == "__main__":
    git_tag()
    print(git_tag())
`

**Comment by rebeccahaines1** [comment]
done in v1.5.0
