### ISSUE TITLE
Add housekeeping/archive functionality

### ISSUE THREAD

**Issue by aledj2** [moka-guys/genomics_server_download#4]
The ArcherDX analysis platform has an auto archive function. 

Each analysis has a folder (which contains all the interim files, eg BAMs, VCFs) at /var/www/analysis/[analysisid]

When an analysis is archived the contents of this file are converted into a tar archive eg /var/www/analysis/[analysisid]/[analysisid].tar.gz

We would need to create a mechanism for uploading this analysis tar.gz to the relevant dnanexus project

The ADX number is not included in the analysisid so would need to peek inside the archive to find the ADX number and then locate the correct project.

The upload agent should be used to ensure data integrity - we may want to install this direct on the archer server (but would need to make sure it's re-installed each time the server is installed, or take the data off the server, back onto the genomics server and upload from there (and delete once uploaded)

**Comment by rebeccahaines1** [comment]
this has been implemented in a separate repo, archer_archiving
